// <auto-generated />
using System;
using IdentityService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328173258_AddEmailVerification")]
    partial class AddEmailVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IdentityService.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StoreCode")
                        .IsUnique();

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Location = "Downtown",
                            Name = "Nexus Main Store",
                            StoreCode = "S001"
                        });
                });

            modelBuilder.Entity("IdentityService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryStoreId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerificationOtpExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PrimaryStoreId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@nexus.com",
                            EmployeeCode = "E001",
                            IsEmailVerified = false,
                            PasswordHash = "Admin@123",
                            PrimaryStoreId = 1,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin@gmail.com",
                            EmployeeCode = "E003",
                            IsEmailVerified = false,
                            PasswordHash = "admin",
                            PrimaryStoreId = 1,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Email = "manager@nexus.com",
                            EmployeeCode = "E004",
                            IsEmailVerified = false,
                            PasswordHash = "Manager@123",
                            PrimaryStoreId = 1,
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            Email = "storemanager@nexus.com",
                            EmployeeCode = "E005",
                            IsEmailVerified = false,
                            PasswordHash = "SManager@123",
                            PrimaryStoreId = 1,
                            Role = "StoreManager"
                        },
                        new
                        {
                            Id = 5,
                            Email = "cashier@nexus.com",
                            EmployeeCode = "E002",
                            IsEmailVerified = false,
                            PasswordHash = "Cashier@123",
                            PrimaryStoreId = 1,
                            Role = "Cashier"
                        });
                });

            modelBuilder.Entity("IdentityService.Models.User", b =>
                {
                    b.HasOne("IdentityService.Models.Store", "PrimaryStore")
                        .WithMany("Users")
                        .HasForeignKey("PrimaryStoreId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("PrimaryStore");
                });

            modelBuilder.Entity("IdentityService.Models.Store", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
